# Generated by Django 4.1.7 on 2023-03-27 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512)),
                ("cpf", models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name="OrganizationCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("description", models.TextField()),
                (
                    "parent_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children_categories",
                        to="organizations.organizationcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512)),
                ("descripton", models.CharField(max_length=512)),
                (
                    "localization",
                    models.TextField(
                        choices=[("CPU", "Cururupu"), ("PHO", "Pinheiro")],
                        default="CPU",
                        max_length=3,
                    ),
                ),
                ("image1", models.ImageField(blank=True, null=True, upload_to="")),
                ("image2", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizations",
                        to="organizations.owner",
                    ),
                ),
            ],
        ),
    ]
