# Generated by Django 4.1.7 on 2023-03-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_remove_product_organization"),
        ("organizations", "0002_organization_products"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="products",
        ),
        migrations.AddField(
            model_name="organization",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="organizations",
                to="products.product",
            ),
        ),
    ]
