# Generated by Django 4.1.7 on 2023-03-27 23:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_remove_product_organization"),
        ("organizations", "0003_remove_organization_products_organization_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="products",
            field=models.ManyToManyField(
                blank=True, related_name="organizations", to="products.product"
            ),
        ),
        migrations.AlterField(
            model_name="owner",
            name="cpf",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{11}$", "Ingrese un CPF válido de 11 dígitos"
                    )
                ],
            ),
        ),
    ]
