# Generated by Django 4.1.7 on 2023-03-27 23:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_organization"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="organization",
        ),
    ]
